
TILESIZE = 32
EASY_SETTINGS = (9,9,10)
INTERMEDIATE_SETTINGS = (16,16,40)
EXPERT_SETTINGS = (30,16,99)
ROWS = 30
COLS = 16
NUM_MINES = 99
SCREEN_WIDTH = ROWS * TILESIZE
SCREEN_HEIGHT = COLS * TILESIZE
SCREEN_DIMS = (SCREEN_WIDTH,SCREEN_HEIGHT)
HEADER_HEIGHT = 2 * TILESIZE
DEFAULT_TIME = '000'

DIM_BOUNDARIES = (1,99)

UNKNOWN = 0

REVEALED = 1
FLAGGED = 2

NUMBER = 1
OPENING = 2
MINE = 3
BLACK = (0,0,0)


