
TILESIZE = 32
SUGGESTIONSIZE = 32
EASY_SETTINGS = (9,9,10)
INTERMEDIATE_SETTINGS = (16,16,40)
EXPERT_SETTINGS = (30,16,99)
ROWS = 30
COLS = 16
NUM_MINES = 99

# ROWS = 16
# COLS = 16
# NUM_MINES = 10
SCREEN_WIDTH = 30 * TILESIZE
SCREEN_HEIGHT = 16 * TILESIZE
SCREEN_DIMS = (SCREEN_WIDTH,SCREEN_HEIGHT)
HEADER_HEIGHT = 2 * TILESIZE
DEFAULT_TIME = '000'

# Three-panel layout constants
LEFT_PANEL_WIDTH = 220
RIGHT_PANEL_WIDTH = 220
PANEL_PADDING = 10
MIN_WINDOW_HEIGHT = 520

# Largest board we layout for (expert). Window is fixed to this size.
MAX_BOARD_ROWS = max(EASY_SETTINGS[0], INTERMEDIATE_SETTINGS[0], EXPERT_SETTINGS[0])
MAX_BOARD_COLS = max(EASY_SETTINGS[1], INTERMEDIATE_SETTINGS[1], EXPERT_SETTINGS[1])
MAX_BOARD_WIDTH = MAX_BOARD_ROWS * TILESIZE
MAX_BOARD_HEIGHT = MAX_BOARD_COLS * TILESIZE
BOARD_VIEWPORT_WIDTH = MAX_BOARD_WIDTH
BOARD_VIEWPORT_HEIGHT = MAX_BOARD_HEIGHT
WINDOW_WIDTH = LEFT_PANEL_WIDTH + MAX_BOARD_WIDTH + RIGHT_PANEL_WIDTH
WINDOW_HEIGHT = max(HEADER_HEIGHT + MAX_BOARD_HEIGHT, MIN_WINDOW_HEIGHT)

DIM_BOUNDARIES = (1,99)

UNKNOWN = 0

REVEALED = 1
FLAGGED = 2

NUMBER = 1
OPENING = 2
MINE = 3
BLACK = (0,0,0)



